version: "3.4"

services:
  account-service:
    build:
      context: ./account-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
    ports:
      - "3030:3333"
    volumes:
      - ./account-service:/app    
    networks:
      - app-network
    restart: unless-stopped

  inventory-service:
    build:
      context: ./inventory-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
    ports:
      - "3031:3333"
    volumes:
      - ./inventory-service:/app    
    networks:
      - app-network
    restart: unless-stopped

  cart-service:
    build:
      context: ./cart-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
    ports:
      - "3032:3333"
    volumes:
      - ./cart-service:/app    
    networks:
      - app-network
    restart: unless-stopped

  discovery:
    image: consul:latest
    command: "agent"
    ports:
      - "8500:8500"
      - "8600:53/tcp"
      - "8600:53/udp"
    volumes:
      - ./discovery/server.json:/consul/config/server.json:ro
    networks:
      - app-network
    restart: always
  
networks:
  app-network:
    driver: bridge